added loading page
manga-easy/manga_easy_coffee_cup pull request #21
Opened 2023-06-08 03:19 UTC by BrunoAlm

Para usar, é preciso passar o atributo double value do widget LinearProgressIndicator
o atributo double animationValue, vai de 0.0 à 1.0

O ideal é reconstruir esse widget a cada frame passando um novo value, assim a barra de progressão aumenta.
![loading-gif](https://github.com/manga-easy/manga_easy_coffee_cup/assets/65208006/2ac34e76-3a5b-4176-a291-568cccbb422f)

2023-06-09 16:48 UTC, cledsonv requested changes
otima adiçao do loading page, mas por que mudou outros arquivos alem de adicionar o loading page?,  Foi uma mudança desnecessária ja que com isso vai ter que trocar so um nome de variavel no restante do aplicativo

2023-06-11 05:49 UTC, cledsonv approved these changes

2023-06-11 05:53 UTC, lucascardo12 approved these changes

2023-06-11 05:53 UTC, lucascardo12 commented on lib/features/pages/loading_page.dart
> +        Image(
Pq não usa o CoffeeImage, ele n precisa por o widget Image.

2023-06-11 05:53 UTC, lucascardo12 commented on lib/features/pages/loading_page.dart
> +          borderRadius: ThemeService.of.borderRadius,
existe esse parâmetro borderRadius?

2023-06-11 06:01 UTC, merged