Me 374 new search bar
manga-easy/manga_easy_coffee_cup pull request #25
Opened 2023-06-24 01:21 UTC by BrunoAlm

PR referente a barra de pesquisa sugerida pelo Niet, no [figma do histórico](https://www.figma.com/proto/7BgReXXvCvywqoxFYdkDyi/Historico?type=design&node-id=1-2&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A2)

2023-06-24 15:34 UTC, lucascardo12 requested changes

2023-06-24 15:34 UTC, lucascardo12 commented on lib/features/fields/new_coffe_search_field.dart
> +class NewCoffeeSearchField extends StatelessWidget {
O widget não pode começar com new, foge do padrão do DS

2023-06-24 20:38 UTC, BrunoAlm commented on lib/features/fields/new_coffe_search_field.dart
> +class NewCoffeeSearchField extends StatelessWidget {
renomeei e removi o antigo

2023-06-25 04:19 UTC, lucascardo12 approved these changes

2023-06-25 04:32 UTC, cledsonv approved these changes

2023-06-30 02:06 UTC, merged