Me 470 melhorar o novo coffee field  e adicionar maskFilter no text
manga-easy/manga_easy_coffee_cup pull request #27
Opened 2023-07-05 16:52 UTC by cledsonv

2023-07-05 23:45 UTC, BrunoAlm approved these changes

2023-07-06 00:24 UTC, lucascardo12 requested changes

2023-07-06 00:24 UTC, lucascardo12 commented on lib/features/fields/coffee_field.dart
> +            text: 'Senha atual',
não pode ter texto fixo.

2023-07-06 00:24 UTC, lucascardo12 commented on lib/features/fields/coffee_field.dart
> -      height: height ?? 54,
e esse parametro de tamanho n vai ser mais usado ? o margin tbm.

2023-07-06 23:05 UTC, cledsonv commented on lib/features/fields/coffee_field.dart
> -      height: height ?? 54,
Não há necessidade mas em usar tamanho no Container, e sobre o margim acredito que ele nao seja nescessario ja que pode ser especificado pra tela em geral

2023-07-06 23:09 UTC, cledsonv commented on lib/features/fields/coffee_field.dart
> +            text: 'Senha atual',
ja foi resolvido isso

2023-07-08 23:27 UTC, BrunoAlm commented on lib/features/fields/coffee_field.dart
> -      height: height ?? 54,
Alterei toda a estrutura do código, analisem

2023-07-10 16:45 UTC, BrunoAlm approved these changes

2023-07-21 02:12 UTC, lucascardo12 approved these changes
Boa agora vai ficar mais organizado os parametros

2023-07-21 02:16 UTC, merged